[build-system]
requires = [
    "setuptools",
    "numpy",
    "cython",
]
build-backend = "setuptools.build_meta"

[project]
name = "pyat"
requires-python = ">=3.8"
authors = [{name = "Yan‑Rong Li", email = "liyropt@gmail.com"}]
dynamic = ["version", "dependencies"]

[project.optional-dependencies]
docs = [
    "sphinx>=7.0",
    "numpydoc>=1.5",
    "sphinx-rtd-theme>=1.3",
]
